version: '3.8'

services:
  back-end:
    build:
      context: ./back-end
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production

  front-end:
    build:
      context: ./front-end
    ports:
      - "80:80"
    volumes:
      - ./nginx-config:/etc/nginx/conf.d 
    environment:
      - NODE_ENV=production