name: Docker CI

on:
  push:
    branches: [ "test-branch" ]
  pull_request:
    branches: [ "test-branch" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and run Dockercd  containers
      run: |
        docker-compose up --build -d
        docker-compose ps
